<?php

/* custom routes generated by CRUD */
Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('clients', 'ClientsController');
	Route::get('clients/{id}/delete', array('as' => 'admin.clients.delete', 'uses' => 'ClientsController@getDelete'));
	Route::get('clients/{id}/confirm-delete', array('as' => 'admin.clients.confirm-delete', 'uses' => 'ClientsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('attorneys', 'AttorneysController');
	Route::get('attorneys/{id}/delete', array('as' => 'admin.attorneys.delete', 'uses' => 'AttorneysController@getDelete'));
	Route::get('attorneys/{id}/confirm-delete', array('as' => 'admin.attorneys.confirm-delete', 'uses' => 'AttorneysController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('articles', 'ArticlesController');
	Route::get('articles/{id}/delete', array('as' => 'admin.articles.delete', 'uses' => 'ArticlesController@getDelete'));
	Route::get('articles/{id}/confirm-delete', array('as' => 'admin.articles.confirm-delete', 'uses' => 'ArticlesController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('practiceareas', 'PracticeareasController');
	Route::get('practiceareas/{id}/delete', array('as' => 'admin.practiceareas.delete', 'uses' => 'PracticeareasController@getDelete'));
	Route::get('practiceareas/{id}/confirm-delete', array('as' => 'admin.practiceareas.confirm-delete', 'uses' => 'PracticeareasController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('similars', 'SimilarsController');
	Route::get('similars/{id}/delete', array('as' => 'admin.similars.delete', 'uses' => 'SimilarsController@getDelete'));
	Route::get('similars/{id}/confirm-delete', array('as' => 'admin.similars.confirm-delete', 'uses' => 'SimilarsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('templates', 'TemplatesController');
	Route::get('templates/{id}/delete', array('as' => 'admin.templates.delete', 'uses' => 'TemplatesController@getDelete'));
	Route::get('templates/{id}/confirm-delete', array('as' => 'admin.templates.confirm-delete', 'uses' => 'TemplatesController@getModalDelete'));
});